# Generated by Django 3.2.10 on 2022-01-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
        ('profiles', '0004_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationinstitute',
            options={'verbose_name': 'Educational Institute'},
        ),
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'verbose_name': 'Education Level'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='position.position'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
