# Generated by Django 3.2.10 on 2022-01-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Salary', 'verbose_name_plural': 'Salaries'},
        ),
    ]
