# Generated by Django 3.2.10 on 2022-01-23 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20220122_1507'),
        ('salaries', '0002_alter_salary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.district'),
        ),
    ]
