# Generated by Django 3.2.10 on 2022-01-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20220120_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
